cd /Videos/peticion287
rm *.avi
cd /Videos/peticion288
rm *.avi
cd /Videos/peticion289
rm *.avi
cd /Videos/peticion290
rm *.avi
cd /Videos/peticion291
rm *.avi
cd /Videos/peticion292
rm *.avi
cd /Videos/peticion293
rm *.avi
cd /Videos/peticion294
rm *.avi
cd /Videos/peticion295
rm *.avi
cd /Videos/peticion296
rm *.avi
cd /Videos/peticion297
rm *.avi
cd /Videos/peticion298
rm *.avi
cd /Videos/peticion299
rm *.avi
cd /Videos/peticion300
rm *.avi
cd /Videos/peticion301
rm *.avi
cd /Videos/peticion302
rm *.avi
cd /Videos/peticion303
rm *.avi
cd /Videos/peticion304
rm *.avi
cd /Videos/peticion305
rm *.avi
cd /Videos/peticion306
rm *.avi
cd /Videos/peticion307
rm *.avi
cd /Videos/peticion308
rm *.avi
cd /Videos/peticion309
rm *.avi
cd /Videos/peticion310
rm *.avi
